#!/bin/bash

scp server.jar 2.2:/home/servisofts/servicios/kolping/entornos/kolping/servicios/kolping/
# ssh 10 'cd ~/servicios/kolping/ && ./servisofts.sh down'
# ssh 10 'cd ~/servicios/kolping/ && ./servisofts.sh up -d'

#scp -r /u01/servisoftsFiles/kolping/* 2.2:/home/servisofts/servicios/kolping/entornos/kolping/servisoftsFiles/kolping/